import { Inter } from "next/font/google";
import "./globals.css";
import BaseLayout from "./baseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce iBOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
