import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import BaseLayout from "../baseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce iBOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
