import { Inter, Barlow } from "next/font/google";
import { Toaster } from "react-hot-toast";
import BaseLayout from "./baseLayout";
import Head from "next/head";

const barlow = Barlow({
  weight: "400",
  preload: false,
});

export const metadata = {
  title: "E-commerce iBOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
